# Generated by Django 5.1.15 on 2026-06-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('seniority', models.CharField(blank=True, choices=[('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], max_length=20)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('work_mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='onsite', max_length=20)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('part_time', 'Part-time')], default='full_time', max_length=20)),
                ('experience_min', models.PositiveSmallIntegerField(default=0)),
                ('experience_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_period', models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('hour', 'Hour')], default='year', max_length=10)),
                ('equity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('equity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('apply_url', models.URLField()),
                ('apply_email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, max_length=160)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_score', models.PositiveSmallIntegerField(default=0)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to='accounts.recruiterprofile')),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], default='submitted', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='navijob', max_length=120)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='resumes.resume')),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['slug'], name='jobs_slug_874285_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'published_at'], name='jobs_is_acti_154980_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['work_mode', 'job_type'], name='jobs_work_mo_b8e3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_by', 'status'], name='jobs_posted__302307_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_premium', 'premium_score'], name='jobs_is_prem_3cb693_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='job_applica_job_id_e29281_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='job_applica_applica_435597_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['submitted_at'], name='job_applica_submitt_ad86f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_application_per_job_applicant'),
        ),
    ]
