# Generated by Django 5.1.15 on 2026-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(blank=True, choices=[('idea', 'Idea'), ('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('growth', 'Growth'), ('public', 'Public')], max_length=20)),
                ('company_size', models.CharField(blank=True, choices=[('1_10', '1-10'), ('11_50', '11-50'), ('51_200', '51-200'), ('201_500', '201-500'), ('500_plus', '500+')], max_length=20)),
                ('funding_summary', models.CharField(blank=True, max_length=180)),
                ('headquarters', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('careers_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium_partner', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='companies_slug_e0676c_idx'), models.Index(fields=['is_verified', 'is_premium_partner'], name='companies_is_veri_e6cb1e_idx'), models.Index(fields=['stage', 'industry'], name='companies_stage_1e6cda_idx')],
            },
        ),
    ]
